### ISSUE TITLE
Security records

### ISSUE THREAD

**Issue by Pockets-byte** [BlueColonySS13/BlueColonySS13#104]
Security records do not persist round-to round, making it extremely difficult to keep track of criminals
security also has no access to modular computer sec records at all, nor fine machines, and officers and the warden don't have access to portable scanner things, which also don't work even as CoP

records need to save for us to maintain any semblance of law and order, and the ability to use security machines would be greatly appreciated 
#### Additional info:
master - 2022-01-06
b6bae115163f665284797b80c676b5a1d8734784

**Comment by Lilligaant** [comment]
BC has a discord for keeping all criminal records for the server,
